---
- hosts: all
  become: yes
  tasks:
 
  - name: Copy stamp.sh
    template:
      src: files/stamp/stamp.sh.j2
      dest: "{{ stamp_lin_bindir }}/stamp.sh"
      owner: root
      group: root
      mode: 0755
    when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or
          (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 16)
 
  - name: Copy stamp.service
    template:
      src: files/stamp/stamp.service.j2
      dest: /etc/systemd/system/stamp.service
      owner: root
      group: root
      mode: 0644
    notify:
      - stamp.service Reload
    when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or
          (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 16)
     
  - name: Start stamp.service with daemon-reload
    systemd:
      state: started
      daemon_reload: yes
      name: stamp
    when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or
          (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 16)
          
  - name: Copy stamp.py
    win_template:
      src: files/stamp/stamp.py.j2
      dest: {{ stamp_win_bindir }}\stamp.py 
    when: ansible_os_family == "Windows"

  - name: Copy SMWinservice.py
    win_copy:
      src: files/stamp/SMWinservice.py
      dest: {{ stamp_lin_bindir }}\SMWinservice.py 
    when: ansible_os_family == "Windows"
    
  - name: Register Stamp Service
    win_command: python stamp.py install
    args:
      chdir: {{ stamp_lin_bindir }}\
    when: ansible_os_family == "Windows"
    
  - name: Start Stamp Service
    win_service:
      name: Stamp
      start_mode: auto
      state: started
      username: {{ stamp_user }}
    when: ansible_os_family == "Windows"
    
  - name: Set Stamp Service Recovery
    win_command: SC failure Stamp actions= restart/60000/restart/60000/""/60000 reset= 86400
    when: ansible_os_family == "Windows"    
     
  handlers:
  - name: stamp.service Reload
    systemd:
      state: restarted
      name: stamp
